name: test obten nombre rama con el contexto

on: workflow_dispatch

jobs:
  primer-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: nota
        run: echo "nota ${{ github.ref }}"
        
      - name: obten rama string
        run: |
          echo "se ejecuto en la rama: ${{ github.ref_name }}"