name: test suma con salida en un artefacto
on:
  push:
    branches:
      - main

jobs:
  job-sube-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: usa checkouts
        uses: actions/checkout@v4

      - name: instala python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: ejecuta test
        run: |
          python test.py 4 3
          python test.py 12 5
          python test.py 4.4 8.2
          python test.py 32.1 1e3

      - name: sube artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-suma
          path: mi_test.txt

  job-download-artifact:
    needs: job-sube-artifact
    runs-on: ubuntu-latest
    steps:
      - name: descarga artifact
        uses: actions/download-artifact@v4
        with:
          name: test-suma

      - name: muestra el contenido del artifact
        run: cat mi_test.txt