name: escritura y lectura de archivo

on:
  - workflow-dispatch
  
jobs:
  job_creacion:
    runs-on: ubuntu-latest
    
    steps:
      - name: crear txt
        run: touch archivo.txt
        
      - name: insertar contenido
        run: echo "texto de muestra" >> archivo.txt

      - name: lee txt
        run: cat archivo.txt