name: escritura y lectura de archivo

on:
  - workflow_dispatch

jobs:
  job_creacion:
    runs-on: ubuntu-latest
    env:
      mifile: archivo
    
    steps:
      - name: crear txt
        run: touch archivo.txt
        
      - name: insertar contenido
        run: echo "texto de muestra para $mifile" >> archivo.txt

      - name: lee txt
        run: cat $mifile.txt